### ISSUE TITLE
dat clone hanging at 17%

### ISSUE THREAD

**Issue by alx** [beatsaver/beatsaver-laravel#58]
Hi,

I'd like to clone the `dat` dataset - `dat://c0eadf29a2b9e110758bbb47690415a42ff236176d045d234c52efdff7ff0097` - but it hangs at 17%

Does it mean that the full dataset is not available on dat ? Or is there another issue on my side ?

I've got 2 servers at separate locations trying to get the full dataset.

Thanks and have a nice day,

Alex

PS: the live `dat` repository at `dat://3c3c78834cb5ac91b70ab28c6ecc0621190b92fc61e9c8154ea2734447afd5dd` is also unreachable.

**Comment by beatsaver** [comment]
Dat is still indexing, give it a few days, its a ton of files and DAT is wanting to take 100% CPU on the box,
